# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='green', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
